apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: environments
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          dev: 'true'
      values:
        path: dev
  - clusters:
      selector:
        matchLabels:
          stage: 'true'
      values:
        path: stage
  - clusters:
      selector:
        matchLabels:
          prod: 'true'
      values:
        path: prod
  template:
    metadata:
      name: 'kd-{{values.path}}-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/noahburrell0/helm-demo-v2.git
        targetRevision: main
        path: 'env/{{values.path}}'
      destination:
        server: '{{server}}'
        namespace: 'kd-{{values.path}}'
      # syncPolicy:
      #   automated:
          # prune: true
        # syncOptions:
        # - CreateNamespace=true